name: ASM

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    defaults:
      run:
        working-directory: ./asm
    steps:
      - uses: actions/checkout@v3

      - name: Docker
        uses: addnab/docker-run-action@v3
        with:
          image: devkitpro/devkita64
          options: -v ${{ github.workspace }}:/tmp
          run: |
            ls /tmp -a
            cd /tmp/asm
            cp -r ./patches/diffs actual-patch-diffs
            cp -r ./additions/diffs actual-additions-diffs
            python3 -m pip install -r req-dev-requirements.txt
            python3 assemble.py
            DIFF=$(diff -qr actual-patch-diffs patches/diffs)
            if [ "$DIFF" != "" ]
            then
                echo "Patches diffs did not match"
                echo "If you are sure you ran assemble.py before pushing, make sure to update devkitPro"
                echo "QUICKFIX: update devkitPro"
                exit 1
            fi
            DIFF=$(diff -qr actual-additions-diffs additions/diffs)
            if [ "$DIFF" != "" ]
            then
                echo "Patches diffs did not match"
                echo "If you are sure you ran assemble.py before pushing, make sure to update devkitPro"
                echo "QUICKFIX: update devkitPro"
                exit 1
            fi

      # - name: Get DEVKITARM env var
      #   run: |
      #     echo | docker ps --format "{{.Names}}"
      #     DEVKITARM=$(docker exec devkitpro/devkita64 env | grep DEVKITARM | cut -d'=' -f2)

      # - name: Copy existing asm diffs
      #   run: |
      #     cp -r ./patches/diffs actual-patch-diffs
      #     cp -r ./additions/diffs actual-additions-diffs
      # - name: Run assemble.py
      #   run: python assemble.py
      # - name: Compare patches diffs
      #   run: |
      #     DIFF=$(diff -qr actual-patch-diffs patches/diffs)
      #     if [ "$DIFF" != "" ]
      #     then
      #         echo "Patches diffs did not match"
      #         echo "If you are sure you ran assemble.py before pushing, make sure to update devkitPro"
      #         echo "QUICKFIX: update devkitPro"
      #         exit 1
      #     fi
      # - name: Compare additions diffs
      #   run: |
      #     DIFF=$(diff -qr actual-additions-diffs additions/diffs)
      #     if [ "$DIFF" != "" ]
      #     then
      #         echo "Patches diffs did not match"
      #         echo "If you are sure you ran assemble.py before pushing, make sure to update devkitPro"
      #         echo "QUICKFIX: update devkitPro"
      #         exit 1
      #     fi
